#!/bin/bash
export LC_ALL=C.UTF-8 #prevents grep error

url=localhost:3003/upload/tenantA
filePath=$1
filename=$(echo "$filePath" | grep -oP "(?<=/)[^/]+$")

options='-X POST '
response=$(curl $options \
    -H "Content-Type: application/octet-stream" \
    -H "Content-Disposition: attachment; filename=${filename}" \
    --data-binary "@${filePath}" \
    $url)
printf '%s\n' "$response"
