name: Deploy and Test GitHub Package

on: [push]

env:
   REGISTRY: ghcr.io
   DOCKER_IMAGE_NAME: ${{ github.repository }}
   URL_AUTH_SERVICE: localhost:8090/authToken


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case DOCKER_IMAGE_NAME
        run: echo "DOCKER_IMAGE_NAME=$(echo $DOCKER_IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $REGISTRY/$DOCKER_IMAGE_NAME .

      - name: Build and Push Docker image to GitHub Packages
        run: |
          VERSION="$(egrep '"version"\s*:' package.json | cut -d \" -f 4)"
          docker build -t $REGISTRY/$DOCKER_IMAGE_NAME:$VERSION -t $REGISTRY/$DOCKER_IMAGE_NAME:latest .
          echo $VERSION
          if docker pull "$REGISTRY/$DOCKER_IMAGE_NAME:$VERSION"; then
            echo "Version already built $REGISTRY/$DOCKER_IMAGE_NAME:$VERSION, aborting." >&2
            exit 1
          fi
          docker image ls
          docker push "$REGISTRY/$DOCKER_IMAGE_NAME:$VERSION"
          docker push "$REGISTRY/$DOCKER_IMAGE_NAME:latest"



  test-newly-updated-image-locally:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          printf "
            URL_AUTH_SERVICE=$URL_AUTH_SERVICE\n
            MONGO_URL=url_to_the_mongo_instance_local_for_the_job\n
            DB_NAME=${{ secrets.DB_NAME }}
            " > .env

      - name: Lower case DOCKER_IMAGE_NAME
        run: echo "DOCKER_IMAGE_NAME=$(echo $DOCKER_IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull Docker image
        run: docker pull $REGISTRY/$DOCKER_IMAGE_NAME

      - name: Run Docker container
        run: |
          (timeout 60s docker run --env-file "$(pwd)/.env" $REGISTRY/$DOCKER_IMAGE_NAME) ||
          if [ $? -eq 124 ]; then
            echo "OK, timeout error is acceptable."
          else
            exit $?
          fi
        continue-on-error: true